//! AI tool instruction file templates.
//!
//! These templates are generated by `agit init` to automatically
//! configure AI coding assistants to log their thoughts to AGIT.

mod claude;
mod cursor;

pub use claude::CLAUDE_MD_TEMPLATE;
pub use cursor::CURSORRULES_TEMPLATE;

/// All template files that should be generated by `agit init`.
pub const TEMPLATE_FILES: &[(&str, &str)] = &[
    ("CLAUDE.md", CLAUDE_MD_TEMPLATE),
    (".cursorrules", CURSORRULES_TEMPLATE),
];
